### ISSUE TITLE
Skip gitmoji as dependency

### ISSUE THREAD

**Issue by tjoskar** [tjoskar/gitmoji-commit-hook#18]
Hi,

I'm using this project a lot and I really like it but the number of emojis in [gitmoji](https://github.com/carloscuesta/gitmoji/) has started to grow ridiculously high and it has started to get annoying when I go throw the list before I can create a commit.

When I created this project, some time ago, I copied the emoji list from atoms [CONTRIBUTING](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) guide which has 12 emojis. gitmoji has, for the time being, 49! 

Two suggestions:

1. We introduce the ability to whitelist/blacklist emoji through a config file. eg.
```
// gitmoji.json
{
  "blacklist": [ "Adding logs", "Performing database related changes" ]
}
```

2. We skip `gitmoji` altogether and creating a new, smaller, list of emoji. Something like:

```diff
🎨: Improving structure / format of the code.
⚡️: Improving performance.
🔥: Removing code or files.
🐛: Fixing a bug.
🚑: Critical hotfix
✨: Introducing new features.
📝: Writing docs.
-🚀: Deploying stuff.
💄: Updating the UI and style files.
-🎉: Initial commit. // This is a one-time only task, I don't want to see this is the list
✅: Adding tests.
-🔒: Fixing security issues. // Security issues are bugs
-🍎: Fixing something on macOS. // Only cross platform projects (as react native or electron) can use these and I think it is not common to fix a bug on only one platform.
-🐧: Fixing something on Linux.
-🏁: Fixing something on Windows.
-🤖: Fixing something on Android.
-🍏: Fixing something on iOS.
-🔖: Releasing / Version tags. // I don't see the use case for this
🚨: Removing linter warnings.
🚧: Work in progress.
-💚: Fixing CI Build. // Can use "Changing configuration files." for this one or some other applicable emoji
⬇️: Downgrading dependencies.
⬆️: Upgrading dependencies.
-👷: Adding CI build system. // This happens usually only once
-📈: Adding analytics or tracking code. // This happens usually only once
🔨: Refactoring code.
-➖: Removing a dependency // You are hopefully doing something more
-🐳: Work about Docker. // What about Vagrant or some other container?
-➕: Adding a dependency // You are hopefully doing something more
🔧: Changing configuration files.
-🌐: Internationalization and localization.
✏️: Fixing typos.
-💩: Writing bad code that needs to be improved. // Can use "Work in progress."
⏪: Reverting changes.
🔀: Merging branches.
-📦: Updating compiled files or packages.
👽: Updating code due to external API changes.
-🚚: Moving or renaming files. // Use "Refactoring code."
-📄: Adding or updating license.
💥: Introducing breaking changes.
-🍱: Adding or updating assets.
-👌: Updating code due to code review changes.
-♿️: Improving accessibility.
-💡: Documenting source code.
-🍻: Writing code drunkenly.
-💬: Updating text and literals
-🗃: Performing database related changes.
-🔊: Adding logs.
-🔇: Removing logs.
```

I'm voting for suggestion 2, namely that we skip gitmoji altogether and uses our own, local, list of emojis. I'm open for discussion which emojis should or should not be included.

What do you say @welcoMattic, @Gyran, @sidgonuts?

**Comment by welcoMattic** [comment]
Hi! I'm not against the idea, but the cleaning is really hard like that. 
Personally, I used a lot Docker things, even I fix some bugs on iOS for responsive issues.
On all my projects, I have CI, I18N, accessibility issues ...

So, may be we should publish the full list, and make it customizable by each user?

WDYT?

**Comment by sidgonuts** [comment]
I agree with @welcoMattic - I think we should publish the full list, and make it customizable. Probably best to do this with a config file that the user can edit.

**Comment by tjoskar** [comment]
I hear you :) I will create a pull request with a solution for suggestion 1 then (customizable).
