### ISSUE TITLE
Use gitmoji 

### ISSUE THREAD

**Issue by welcoMattic** [tjoskar/gitmoji-commit-hook#3]
Ref #2 

It would be nice to rename the repo to `gitmoji-commit-hook` ;)

**Comment by tjoskar** [comment]
Sure, it is fine with me. I saw that you are the owner of `emoji-commit-hook` on npm so it should be fine. We can rename it after the PR has been merged.

**Comment by welcoMattic** [comment]
Yeah! I just delete my fork, we continue the job here!
Thanks for merging 🎉
